security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: argon2i
    providers:
        data_base:
            entity:
                class: App\Entity\User
    role_hierarchy:
        ROLE_USER: ROLE_ANONYMOUS
        ROLE_HELPER: ROLE_USER
        ROLE_MOD: ROLE_HELPER # For Moderators
        ROLE_DEV: ROLE_HELPER # For Developpers Contributors
        ROLE_DESIGN: ROLE_HELPER # For Designers Contributors
        ROLE_TRANS: ROLE_HELPER # For Translators Contributors
        ROLE_ADMIN: [ROLE_MOD, ROLE_DEV, ROLE_DESIGN, ROLE_TRANS] # For Administrators
        ROLE_ROOT: ROLE_ADMIN # For Super Users
        ROLE_OWNER: ROLE_ROOT # For Owner, we recommend to assign this role to only ONE user
    #access_control:
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/helper', roles: ROLE_HELPER }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/mod', roles: ROLE_MOD }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/dev', roles: ROLE_DEV }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/design', roles: ROLE_DESIGN }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/trans', roles: ROLE_TRANS }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/admin', roles: ROLE_ADMIN }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/root', roles: ROLE_ROOT }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/admin/manage_roles/admin', roles: ROLE_ROOT }
    #    - { path: '^/[a-z]{2}(_[A-Z]{2})?/admin/manage_roles/root', roles: ROLE_OWNER }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # pattern: ^/
            # anonymous: /{_locale}/signup
            anonymous: ~
            form_login:
                username_parameter: 'log_in[username]'
                password_parameter: 'log_in[password]'
                login_path: app_login
                check_path: app_login
                default_target_path: app_index
                failure_path: app_login
            remember_me:
                secret: '%kernel.secret%'
                name: remember_me
                lifetime: 15600000
                remember_me_parameter: log_in[rememberme]
                path: /
            logout:
                path: app_logout
                target: app_login
                delete_cookies:
                    remember_me: { path: / }
                invalidate_session: false
            provider: data_base

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
