ROLE_ANONYMOUS:
    user:
        user_submit: 'Yes'
        user_edit: 'No'
        user_edit_other: 'No'
        user_delete: 'No'
        user_delete_other: 'No'
        user_review: false
    post:
        post_submit: 'No'
        post_edit: 'No'
        post_edit_other: 'No'
        post_delete: 'No'
        post_delete_other: 'No'
        post_option_color: false
        post_option_textsize: false
        post_review: false
    comment:
        comment_submit: 'No'
        comment_edit: 'No'
        comment_edit_other: 'No'
        comment_delete: 'No'
        comment_delete_other: 'No'
        comment_review: false
    survey:
        survey_submit: 'No'
        survey_edit: 'No'
        survey_edit_other: 'No'
        survey_delete: 'No'
        survey_delete_other: 'No'
        survey_review: false
    report:
        report_submit: false
        report_review: false
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: false
    laws:
        laws_submit: 'No'
        laws_review: false
    administration:
        administration_access: false
ROLE_USER:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'No'
        user_delete: 'Yes'
        user_delete_other: 'No'
        user_review: false
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'No'
        post_delete: 'Yes'
        post_delete_other: 'No'
        post_option_color: true
        post_option_textsize: true
        post_review: false
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'No'
        comment_delete: 'Yes'
        comment_delete_other: 'No'
        comment_review: false
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Needs Review'
        survey_edit_other: 'No'
        survey_delete: 'Yes'
        survey_delete_other: 'No'
        survey_review: false
    report:
        report_submit: true
        report_review: false
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'No'
        laws_review: false
    administration:
        administration_access: false
ROLE_HELPER:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Needs Review'
        user_delete: 'Yes'
        user_delete_other: 'Needs Review'
        user_review: false
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Needs Review'
        post_delete: 'Yes'
        post_delete_other: 'Needs Review'
        post_option_color: true
        post_option_textsize: true
        post_review: false
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Needs Review'
        comment_delete: 'Yes'
        comment_delete_other: 'Needs Review'
        comment_review: false
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Needs Review'
        survey_delete: 'Yes'
        survey_delete_other: 'Needs Review'
        survey_review: false
    report:
        report_submit: true
        report_review: false
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Needs Review'
        laws_review: false
    administration:
        administration_access: true
ROLE_MOD:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Yes'
        user_delete: 'Yes'
        user_delete_other: 'Yes'
        user_review: true
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Yes'
        post_delete: 'Yes'
        post_delete_other: 'Yes'
        post_option_color: true
        post_option_textsize: true
        post_review: true
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Yes'
        comment_delete: 'Yes'
        comment_delete_other: 'Yes'
        comment_review: true
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Yes'
        survey_delete: 'Yes'
        survey_delete_other: 'Yes'
        survey_review: true
    report:
        report_submit: true
        report_review: true
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Needs Review'
        laws_review: false
    administration:
        administration_access: true
ROLE_DEV:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Needs Review'
        user_delete: 'Yes'
        user_delete_other: 'Needs Review'
        user_review: false
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Needs Review'
        post_delete: 'Yes'
        post_delete_other: 'Needs Review'
        post_option_color: true
        post_option_textsize: true
        post_review: false
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Needs Review'
        comment_delete: 'Yes'
        comment_delete_other: 'Needs Review'
        comment_review: false
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Needs Review'
        survey_delete: 'Yes'
        survey_delete_other: 'Needs Review'
        survey_review: false
    report:
        report_submit: true
        report_review: false
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Needs Review'
        laws_review: false
    administration:
        administration_access: true
ROLE_DESIGN:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Needs Review'
        user_delete: 'Yes'
        user_delete_other: 'Needs Review'
        user_review: false
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Needs Review'
        post_delete: 'Yes'
        post_delete_other: 'Needs Review'
        post_option_color: true
        post_option_textsize: true
        post_review: false
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Needs Review'
        comment_delete: 'Yes'
        comment_delete_other: 'Needs Review'
        comment_review: false
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Needs Review'
        survey_delete: 'Yes'
        survey_delete_other: 'Needs Review'
        survey_review: false
    report:
        report_submit: true
        report_review: false
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Needs Review'
        laws_review: false
    administration:
        administration_access: true
ROLE_TRANS:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Needs Review'
        user_delete: 'Yes'
        user_delete_other: 'Needs Review'
        user_review: false
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Needs Review'
        post_delete: 'Yes'
        post_delete_other: 'Needs Review'
        post_option_color: true
        post_option_textsize: true
        post_review: false
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Needs Review'
        comment_delete: 'Yes'
        comment_delete_other: 'Needs Review'
        comment_review: false
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Needs Review'
        survey_delete: 'Yes'
        survey_delete_other: 'Needs Review'
        survey_review: false
    report:
        report_submit: true
        report_review: false
    statistics:
        statistics_access: false
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Needs Review'
        laws_review: false
    administration:
        administration_access: true
ROLE_ADMIN:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Yes'
        user_delete: 'Yes'
        user_delete_other: 'Yes'
        user_review: true
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Yes'
        post_delete: 'Yes'
        post_delete_other: 'Yes'
        post_option_color: true
        post_option_textsize: true
        post_review: true
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Yes'
        comment_delete: 'Yes'
        comment_delete_other: 'Yes'
        comment_review: true
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Yes'
        survey_delete: 'Yes'
        survey_delete_other: 'Yes'
        survey_review: true
    report:
        report_submit: true
        report_review: true
    statistics:
        statistics_access: true
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Yes'
        laws_review: true
    administration:
        administration_access: true
ROLE_ROOT:
    user:
        user_submit: 'Yes'
        user_edit: 'Yes'
        user_edit_other: 'Yes'
        user_delete: 'Yes'
        user_delete_other: 'Yes'
        user_review: true
    post:
        post_submit: 'Yes'
        post_edit: 'Yes'
        post_edit_other: 'Yes'
        post_delete: 'Yes'
        post_delete_other: 'Yes'
        post_option_color: true
        post_option_textsize: true
        post_review: true
    comment:
        comment_submit: 'Yes'
        comment_edit: 'Yes'
        comment_edit_other: 'Yes'
        comment_delete: 'Yes'
        comment_delete_other: 'Yes'
        comment_review: true
    survey:
        survey_submit: 'Yes'
        survey_edit: 'Yes'
        survey_edit_other: 'Yes'
        survey_delete: 'Yes'
        survey_delete_other: 'Yes'
        survey_review: true
    report:
        report_submit: true
        report_review: true
    statistics:
        statistics_access: true
    friendship:
        friendship_submit: true
    laws:
        laws_submit: 'Yes'
        laws_review: true
    administration:
        administration_access: true
__META__:
    user:
        user_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        user_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        user_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        user_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        user_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        user_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    post:
        post_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        post_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        post_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        post_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        post_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        post_option_color:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
        post_option_textsize:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
        post_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    comment:
        comment_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        comment_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        comment_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        comment_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        comment_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        comment_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    survey:
        survey_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        survey_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        survey_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        survey_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        survey_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        survey_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    report:
        report_submit:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
        report_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    statistics:
        statistics_access:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    friendship:
        friendship_submit:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    laws:
        laws_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    'Yes': 'Yes'
                    'No': 'No'
                    'Needs Review': 'Needs Review'
            default: 'No'
        laws_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
    administration:
        administration_access:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: false
        administration_tools:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    questions_office: questions_office
                    ideas_office: ideas_office
                    manage_doc: manage_doc
                    submit_modif: submit_modif
                    manage_profiler: manage_profiler
                    source_code: source_code
                    dev_tools: dev_tools
                    gitlab_interface: gitlab_interface
                    manage_themes: manage_themes
                    manage_css: manage_css
                    manage_translations: manage_translations
                    complaints_office: complaints_office
                    investigations: investigations
                    false_accounts: false_accounts
                    manage_community: manage_community
                    contact_administration: contact_administration
                    manage_roles: manage_roles
                    manage_authorization: manage_authorization
                    edit_website: edit_website
                    statistics: statistics
                    sql_interface: sql_interface
                    manage_policy: manage_policy
                multiple: true
            default: {  }
