ANONYMOUS:
    user:
        user_submit: Yes
        user_edit: No
        user_edit_other: No
        user_delete: No
        user_delete_other: No
        user_review: False

    post:
        post_submit: No
        post_edit: No
        post_edit_other: No
        post_delete: No
        post_delete_other: No
        post_option_color: False
        post_option_textsize: False
        post_review: False

    comment:
        comment_submit: No
        comment_edit: No
        comment_edit_other: No
        comment_delete: No
        comment_delete_other: No
        comment_review: False

    survey:
        survey_submit: No
        survey_edit: No
        survey_edit_other: No
        survey_delete: No
        survey_delete_other: No
        survey_review: False

    report:
        report_submit: False
        report_review: False

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: False

    laws:
        laws_submit: No
        laws_review: False

    administration:
        administration_access: False

ROLE_USER:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: No
        user_delete: Yes
        user_delete_other: No
        user_review: False

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: No
        post_delete: Yes
        post_delete_other: No
        post_option_color: True
        post_option_textsize: True
        post_review: False

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: No
        comment_delete: Yes
        comment_delete_other: No
        comment_review: False

    survey:
        survey_submit: Yes
        survey_edit: Needs Review
        survey_edit_other: No
        survey_delete: Yes
        survey_delete_other: No
        survey_review: False

    report:
        report_submit: True
        report_review: False

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: True

    laws:
        laws_submit: No
        laws_review: False

    administration:
        administration_access: False

ROLE_HELPER:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Needs Review
        user_delete: Yes
        user_delete_other: Needs Review
        user_review: False

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Needs Review
        post_delete: Yes
        post_delete_other: Needs Review
        post_option_color: True
        post_option_textsize: True
        post_review: False

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Needs Review
        comment_delete: Yes
        comment_delete_other: Needs Review
        comment_review: False

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Needs Review
        survey_delete: Yes
        survey_delete_other: Needs Review
        survey_review: False

    report:
        report_submit: True
        report_review: False

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Needs Review
        laws_review: False

    administration:
        administration_access: True

ROLE_MOD:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Yes
        user_delete: Yes
        user_delete_other: Yes
        user_review: True

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Yes
        post_delete: Yes
        post_delete_other: Yes
        post_option_color: True
        post_option_textsize: True
        post_review: True

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Yes
        comment_delete: Yes
        comment_delete_other: Yes
        comment_review: True

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Yes
        survey_delete: Yes
        survey_delete_other: Yes
        survey_review: True

    report:
        report_submit: True
        report_review: True

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Needs Review
        laws_review: False

    administration:
        administration_access: True

ROLE_DEV:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Needs Review
        user_delete: Yes
        user_delete_other: Needs Review
        user_review: False

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Needs Review
        post_delete: Yes
        post_delete_other: Needs Review
        post_option_color: True
        post_option_textsize: True
        post_review: False

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Needs Review
        comment_delete: Yes
        comment_delete_other: Needs Review
        comment_review: False

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Needs Review
        survey_delete: Yes
        survey_delete_other: Needs Review
        survey_review: False

    report:
        report_submit: True
        report_review: False

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Needs Review
        laws_review: False

    administration:
        administration_access: True

ROLE_DESIGN:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Needs Review
        user_delete: Yes
        user_delete_other: Needs Review
        user_review: False

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Needs Review
        post_delete: Yes
        post_delete_other: Needs Review
        post_option_color: True
        post_option_textsize: True
        post_review: False

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Needs Review
        comment_delete: Yes
        comment_delete_other: Needs Review
        comment_review: False

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Needs Review
        survey_delete: Yes
        survey_delete_other: Needs Review
        survey_review: False

    report:
        report_submit: True
        report_review: False

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Needs Review
        laws_review: False

    administration:
        administration_access: True

ROLE_TRANS:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Needs Review
        user_delete: Yes
        user_delete_other: Needs Review
        user_review: False

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Needs Review
        post_delete: Yes
        post_delete_other: Needs Review
        post_option_color: True
        post_option_textsize: True
        post_review: False

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Needs Review
        comment_delete: Yes
        comment_delete_other: Needs Review
        comment_review: False

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Needs Review
        survey_delete: Yes
        survey_delete_other: Needs Review
        survey_review: False

    report:
        report_submit: True
        report_review: False

    statistics:
        statistics_access: False

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Needs Review
        laws_review: False

    administration:
        administration_access: True

ROLE_ADMIN:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Yes
        user_delete: Yes
        user_delete_other: Yes
        user_review: True

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Yes
        post_delete: Yes
        post_delete_other: Yes
        post_option_color: True
        post_option_textsize: True
        post_review: True

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Yes
        comment_delete: Yes
        comment_delete_other: Yes
        comment_review: True

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Yes
        survey_delete: Yes
        survey_delete_other: Yes
        survey_review: True

    report:
        report_submit: True
        report_review: True

    statistics:
        statistics_access: True

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Yes
        laws_review: True

    administration:
        administration_access: True

ROLE_ROOT:
    user:
        user_submit: Yes
        user_edit: Yes
        user_edit_other: Yes
        user_delete: Yes
        user_delete_other: Yes
        user_review: True

    post:
        post_submit: Yes
        post_edit: Yes
        post_edit_other: Yes
        post_delete: Yes
        post_delete_other: Yes
        post_option_color: True
        post_option_textsize: True
        post_review: True

    comment:
        comment_submit: Yes
        comment_edit: Yes
        comment_edit_other: Yes
        comment_delete: Yes
        comment_delete_other: Yes
        comment_review: True

    survey:
        survey_submit: Yes
        survey_edit: Yes
        survey_edit_other: Yes
        survey_delete: Yes
        survey_delete_other: Yes
        survey_review: True

    report:
        report_submit: True
        report_review: True

    statistics:
        statistics_access: True

    friendship:
        friendship_submit: True

    laws:
        laws_submit: Yes
        laws_review: True

    administration:
        administration_access: True

__META__:
    user:
        user_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        user_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        user_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        user_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        user_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        user_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    post:
        post_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        post_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        post_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        post_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        post_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        post_option_color:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False
        post_option_textsize:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False
        post_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    comment:
        comment_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        comment_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        comment_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        comment_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        comment_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        comment_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    survey:
        survey_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        survey_edit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        survey_edit_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        survey_delete:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        survey_delete_other:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        survey_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    report:
        report_submit:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False
        report_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    statistics:
        statistics_access:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    friendship:
        friendship_submit:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    laws:
        laws_submit:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    Yes: yes
                    No: no
                    Needs Review: needs_review
            default: No
        laws_review:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False

    administration:
        administration_access:
            input: Symfony\Component\Form\Extension\Core\Type\CheckboxType
            default: False
        administration_tools:
            input: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            input_var:
                choices:
                    - questions_office
                    - ideas_office
                    - manage_doc
                    - submit_modif
                    - manage_profiler
                    - source_code
                    - dev_tools
                    - gitlab_interface
                    - manage_themes
                    - manage_css
                    - manage_translations
                    - complaints_office
                    - investigations
                    - false_accounts
                    - manage_community
                    - contact_administration
                    - manage_roles
                    - manage_authorization
                    - edit_website
                    - statistics
                    - sql_interface
                    - manage_policy
                multiple: True
            default: []
