parameters:
    roles:
        list:
            - ROLE_USER
            - ROLE_HELPER
            - ROLE_MOD
            - ROLE_DEV
            - ROLE_DESIGN
            - ROLE_TRANS
            - ROLE_ADMIN
            - ROLE_ROOT
            - ROLE_OWNER
        alias:
            u: ROLE_USER
            user: ROLE_USER
            h: ROLE_HELPER
            help: ROLE_HELPER
            helper: ROLE_HELPER
            m: ROLE_MOD
            mod: ROLE_MOD
            moderator: ROLE_MOD
            moderation: ROLE_MOD
            d: ROLE_DEV
            dev: ROLE_DEV
            developer: ROLE_DEV
            development: ROLE_DEV
            p: ROLE_DEV
            programmer: ROLE_DEV
            programming: ROLE_DEV
            ds: ROLE_DESIGN
            design: ROLE_DESIGN
            designer: ROLE_DESIGN
            designing: ROLE_DESIGN
            t: ROLE_TRANS
            trans: ROLE_TRANS
            translator: ROLE_TRANS
            translation: ROLE_TRANS
            a: ROLE_ADMIN
            admin: ROLE_ADMIN
            administrator: ROLE_ADMIN
            administration: ROLE_ADMIN
            r: ROLE_ROOT
            root: ROLE_ROOT
            o: ROLE_OWNER
            owner: ROLE_OWNER
            super_root: ROLE_OWNER
            god: ROLE_OWNER
            bdfl: ROLE_OWNER
    authorizations:
        user:
            submit: ROLE_ANONYMOUS
            submit_with_review: NONE
            edit: ROLE_USER
            edit_with_review: NONE
            edit_other_with_review: ROLE_HELPER
            edit_other: ROLE_MOD
            delete: ROLE_USER
            delete_with_review: NONE
            delete_other_with_review: ROLE_HELPER
            delete_other: ROLE_MOD
            review: ROLE_HELPER
            review_other: ROLE_MOD
        post:
            submit: ROLE_USER
            submit_with_review: NONE
            edit: ROLE_USER
            edit_with_review: NONE
            edit_other_with_review: ROLE_HELPER
            edit_other: ROLE_MOD
            delete: ROLE_USER
            delete_with_review: NONE
            delete_other_with_review: ROLE_HELPER
            delete_other: ROLE_MOD
            review: ROLE_HELPER
            review_other: ROLE_MOD
            option_color: ROLE_USER
            option_textsize: ROLE_USER
        comment:
            submit: ROLE_USER
            submit_with_review: NONE
            edit: ROLE_USER
            edit_with_review: NONE
            edit_other_with_review: ROLE_HELPER
            edit_other: ROLE_MOD
            delete: ROLE_USER
            delete_with_review: NONE
            delete_other_with_review: ROLE_HELPER
            delete_other: ROLE_MOD
            review: ROLE_HELPER
            review_other: ROLE_MOD
        survey:
            submit: ROLE_USER
            submit_with_review: NONE
            edit: ROLE_HELPER
            edit_with_review: ROLE_USER
            edit_other_with_review: ROLE_HELPER
            edit_other: ROLE_MOD
            delete: ROLE_USER
            delete_with_review: NONE
            delete_other_with_review: ROLE_HELPER
            delete_other: ROLE_MOD
            review: ROLE_HELPER
            review_other: ROLE_MOD
        report:
            submit: ROLE_USER
            review: ROLE_MOD
        friendship:
            submit: ROLE_USER
        laws:
            submit: ROLE_ADMIN
            submit_with_review: ROLE_MOD
            call_vote: ROLE_ADMIN
            review: ROLE_ADMIN
        administration:
            access: ROLE_HELPER
            accessible:
                questions_office: ROLE_HELPER
                ideas_office: ROLE_HELPER
                manage_doc: ROLE_HELPER
                submit_modif: ROLE_MOD
                manage_profiler: ROLE_DEV
                source_code: ROLE_DEV
                dev_tools: ROLE_DEV
                gitlab_interface: [ROLE_DEV, ROLE_DESIGN]
                manage_themes: ROLE_DESIGN
                manage_css: ROLE_DESIGN
                manage_translations: ROLE_TRANS
                complaints_office: ROLE_MOD
                investigations: ROLE_MOD
                false_accounts: ROLE_MOD
                manage_community: ROLE_MOD
                contact_administration: ROLE_MOD
                manage_roles: ROLE_ADMIN
                manage_authorization: ROLE_ADMIN
                edit_website: ROLE_ROOT
                statistics: ROLE_ROOT
                sql_interface: ROLE_ROOT
                manage_policy: ROLE_ROOT
